### ISSUE TITLE
Real time line chart 

### ISSUE THREAD

**Issue by yuchuqiao** [danielgindi/ios-charts#142]
hi,

Anyone successfully implement a realtime line chart ? Some example to give ? I tried several ways, like: call notifyDatasetChanged() and reloadInputViews.  But that makes the chart completely messed up. 

Thanks.

**Comment by danielgindi** [comment]
You mean for adding data in realtime?

**Comment by knseir** [comment]
Hi Daniel, glad I found this issue.
I'm also trying to add data in realtime. I have a heart rate monitor that sends a heart rate at irregular intervals. every time it does, I call a function that ends with : 

            chart.notifyDataSetChanged()

Only the chart doesn't change until it gets about 5-7 new datapoint 

I know they're not all coming together because I can see them on the console.
I get point 1, 2, 3, ... 7 THEN the chart changes

is there something similar to chart.invalidate ?

**Comment by knseir** [comment]
UPDATE: 

it turns out that the graph was updated automatically. I notices this when I swiped to the right and it showed the new values. However, I had to keep swiping to see them 

even

        chart.setVisibleXRangeMaximum(20)
        chart.moveViewToX(data!.xValCount - 21)

did not move the graph to the new points

**Comment by sunjames** [comment]
Ios - charts can mix after release

**Comment by knseir** [comment]
Hi sunjames, I'm sorry, I don't understand 
'charts can mix after release' ?

**Comment by danielgindi** [comment]
the `moveViewToX` function was fixed, so you should be able to control it in whatever way you like now.
