### ISSUE TITLE
drawCubicEnabled on LineChartView is missing points when Y Values are missing

### ISSUE THREAD

**Issue by louis49** [danielgindi/ios-charts#157]
With this data you can reproduce the bug : 

		var xVals:[String] = ["0", "1", "2", "3", "4", "5", "6"]
		var yVals:[ChartDataEntry] = [
			ChartDataEntry(value: Double(1), xIndex: 1),
			ChartDataEntry(value: Double(5), xIndex: 3),
			ChartDataEntry(value: Double(3), xIndex: 5)
		]
		
		var dataSet:LineChartDataSet = LineChartDataSet(yVals: yVals)
		dataSet.drawCirclesEnabled = false
		dataSet.drawFilledEnabled = true
		dataSet.drawCubicEnabled = true
		
		var data:LineChartData = LineChartData(xVals: xVals, dataSet: dataSet)

![ios simulator screen shot 18 juin 2015 11 54 52](https://cloud.githubusercontent.com/assets/357595/8228672/e907a440-15b0-11e5-85de-1542dc21aad2.png)

**Comment by danielgindi** [comment]
It looks like there's not enough data to complete a cubic curve. We can of course simulate the last coordinate, and we've done that in the past, so this is a bug introduced lately I guess.
Can you confirm that it works when adding another point?

**Comment by louis49** [comment]
Yes it works when adding all points

**Comment by danielgindi** [comment]
I've looked into this - and the problem is the missing y values, which the renderer is no aware of.
@PhilJay do you think that just looping back on the `prev` point and looping forward on the `next` point until we have enough points - is enough to solve this? I know that there are some issues on Android with path sizes and a point could be found futher away on the chart and resulting in a bigger path...

**Comment by PhilJay** [comment]
Yes that could be a solution.
The issue concerning the path only arises if they are significantly larger (in terms of covered pixels) than the screen size.
I think that there still might be some issues in our implementation that cause the "path too big" problem.

**Comment by danielgindi** [comment]
This was solved in a recent commit, last week.
