### ISSUE TITLE
Problem importing framework to Xcode 6.4 in Swift Project

### ISSUE THREAD

**Issue by shaolinjr** [danielgindi/ios-charts#233]
Every time a try to do 'import Charts' a got an message from Xcode, "Xcode encountered a problem, trying to restore" and when I run the project i got a 'segmentation fault: 11'. Can anyone please help me solve this problem?

**Comment by liuxuan30** [comment]
Do you have such problems without the import? Do you have trouble to run chartDemo? I am with Xcode 6.4 and I don't have this issue.

You could also create a new project and try it from there. based on the error message, we cannot tell.

**Comment by danielgindi** [comment]
There are occasional crashes in the compiler, which are fixed in Xcode 7. Unfortunately we cannot do anything about it. If you really want you can omit headers and code from your project until you find the one that causes the "too much complexity" problem for the compiler. When there's too much complexity, the compiler stops with an error signal, and in rare cases Xcode itself crashes.
