### ISSUE TITLE
What's the differences between setAxisMaximum and customAxisMax

### ISSUE THREAD

**Issue by kscorpio** [danielgindi/ios-charts#239]
After init a linecharview like this

              _scaleView.delegate = self;  
               _lineChart.descriptionText = @"";
               _lineChart.noDataTextDescription = @"";
               _lineChart.highlightEnabled = YES;
               _lineChart.dragEnabled = YES;
              [_lineChart setScaleEnabled:YES];
               _lineChart.pinchZoomEnabled = NO;
    
              _lineChart.drawGridBackgroundEnabled = NO;
              _lineChart.legend.position = ChartLegendPositionBelowChartRight;

I find 4 properies :

              [_lineChart.leftAxis setAxisMaximum:200];
              [_lineChart.leftAxis setAxisMinimum:-200];
              _lineChart.leftAxis.customAxisMax = 200;
              _lineChart.leftAxis.customAxisMin = -200;

the _lineChart yAxis is from -1 to +1 and it just can zoom in can not zoom out 
and can not zoom and move in x direction
i have run a demo in android , the chat can zoom and move freely

**Comment by liuxuan30** [comment]
Once you set customAxisMax/Max, it just defines the max range of the axis, so you cannot zoom out I guess if you are not zoomed in first. Because if you try to zoom out the max range, what the range would be is unknown. I don't know android, @PhilJay can you confirm?

axisMaximum/Min is something calculated via `computeAxisValues` or `calcMinMax`, so normally you don't have to change this (and shouldn't)

Once you set customAxisMax/Max, axisMax/Min is set to it:
```Swift
        _yAxis.axisMaximum = !isnan(_yAxis.customAxisMax) ? _yAxis.customAxisMax : maxLeft + Double(topSpaceLeft)
        _yAxis.axisMinimum = !isnan(_yAxis.customAxisMin) ? _yAxis.customAxisMin : minLeft - Double(bottomSpaceLeft)
```

**Comment by kscorpio** [comment]
-  How to achieve  xyAxis zoom in/out infinitely ？
-  How to adjust unit length x y， like X:Y =1:3

**Comment by kscorpio** [comment]
- can the property  customAxisMax/min be changed automaticlly ,when i add point to dataset??

**Comment by liuxuan30** [comment]
I don't believe you can zoom out infinitely... That does not make much sense.

customAxisMax/min means you define the max/min, instead of calculating. When you add point to dataSet, axis max/min are calculated with these values already.

**Comment by SvenMuc** [comment]
I used the following line of codes to zoom in by programatically for example to show just the min and max value of the data. Nevertheless, I haven't tried whether it is still possible to zoom in/out by the gestures.
Important topic for me was to set the `labelCount`correctly. Otherwise you might get strange steps on the axis.

```swift
lineChart.leftAxis.customAxisMin = max(0.0, lineChart.data!.yMin - 1.0)
lineChart.leftAxis.customAxisMax = min(10.0, lineChart.data!.yMax + 1.0)
lineChart.leftAxis.labelCount = Int(lineChart.leftAxis.customAxisMax - lineChart.leftAxis.customAxisMin)
lineChart.leftAxis.startAtZeroEnabled = false
```

**Comment by ricardosousaDev** [comment]
For those who find an issue of not having the customAxisMin/Max working, bare in mind that the dataSet should be added to the graph **after**.
