### ISSUE TITLE
having hard time to put working on version iOS 7.1

### ISSUE THREAD

**Issue by tnmendex** [danielgindi/ios-charts#270]
Hi everyone, i am trying to put working this chart on iOS 7.1 but i am failing.
I know that its something that i am missing but i can't find what. For the version iOS 8 i had no difficult to have put it work.

Already try a lot o things, include almost all the files, i had read the issues of this page and from stackoverflow and noting.

I had create again a new empty project and start from the begin just for testing without garbage of the old project.

So i have this in the file viewController
#import <UIKit/UIKit.h>
#import "Charts.h"
@interface ViewController : UIViewController 
@end

And this on .m
#import "ViewController.h"

@interface ViewController () <ChartViewDelegate>
@end

@implementation ViewController
- (void)viewDidLoad {
    [super viewDidLoad];
}
@end

And even just starting is giving me a problem in <ChartViewDelegate>  giving the error: Cannot find protocol declaration for ‘ChartViewDelegate' i had drag all the swift file and they are in the target.

Here it is the project http://we.tl/NwPueCqfBi

**Comment by liuxuan30** [comment]
take a look at https://github.com/danielgindi/ios-charts/issues/57

BTW, I cannot download it. The website downloading is too fancy and downloaded nothing in my firefox.

**Comment by petester42** [comment]
You dont actually need to do those things. You only need to import your applications swift header. Use `#import "testeIOS7graficos-Swift.h"` instead of `#import "Charts.h"`

Info can be found [here](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html)
![screen shot 2015-08-04 at 8 09 03 am](https://cloud.githubusercontent.com/assets/296718/9060304/68e87042-3a80-11e5-99fc-a93fd3c454e8.png)

**Comment by tnmendex** [comment]
thank you @liuxuan30 and @petester42  for answers...i was trying to write the full bundle "com.training.testeIOS7graficos-Swift.h" that why was not working.

Once again thanks!!! :)
