### ISSUE TITLE
ChartsDemo-swift.h  file not found 

### ISSUE THREAD

**Issue by ahmadabudawod** [danielgindi/ios-charts#31]
I have faced problem which describe by ( ChartsDemo-swift.h file not found )  i want to focused that everything is working correctly only this file isn't imported .
  
![screen shot 2015-04-15 at 2 09 26 pm](https://cloud.githubusercontent.com/assets/862330/7157519/1cbecc38-e379-11e4-9c4a-f9530ee66254.png)

**Comment by vishw3** [comment]
actually it should be  "yourprojectname-swift.h" if you are using in your project.

also in build phase check "Embedded content contains swift code"s should be yes

**Comment by danielgindi** [comment]
Thanks @vishw3

**Comment by ahmadabudawod** [comment]
sorry for late but still have the same error

**Comment by allaire** [comment]
@danielgindi @ahmadabudawod Please see http://stackoverflow.com/a/30648104/277370. When you use embedded framework, I had to do like the answer on SO. Using the `#import <project>-Swift.h` works well when you directly add the library files (`Classes/`) to your project (instead of just adding the `.xcodeproj` and add it to embed frameworks).

I think when you only add the `xcodeproj`, You must import it with `#import "Charts/Charts-Swift.h"`

**Comment by RbeiAppsTeam** [comment]
@allaire  thumbs up. your solution helped me. I am not sure why, but the previous comments of importing #import <project>-Swift.h did not solve the error.

**Comment by mobidever** [comment]
@allaire Thumbs up again. Hey @danielgindi I think the same can be updated for newbies. I was stuck with the same, being newbie to objc-swift bridging. Thanks again @allaire , you saved the day.

**Comment by inix** [comment]
@allaire  
Xcode 8.1,iOS 10.1, I have this issue.
Thank you for your solution.

**Comment by srivastavag8** [comment]
put it in .m file and leave a forward declaration in .h
