### ISSUE TITLE
Daniel are you really fit?

### ISSUE THREAD

**Issue by gjpc** [danielgindi/ios-charts#339]
I have been working with ios-charts for over 3 months. I like it. it is fast. It is clean code. But every time I try to make a contribution I am met with you obstinate disdain. I am wondering if it is your deep breed racism that is the root of these rejections. I was having a lively technical discussion trying to explain to you the necessity of having a scatter chart that preserved the ordered acquisition of XY pairs over time. You over and over again insisted that it would never be a factor for graphing data. And then in your post used the Italian word Capiche, apparently assuming I am still attached to heritage that my family left behind over a hundred years ago. I was insulted. I try to use google to look up a suitable Hebrew epithet.

I have over and over again shown to you that non-ordered XY pairs are necessary to plot necessary data. You told me to make a branch with my mods as a new chart IndependentScatterCharts. I did.. You then told me there were "the commits were a mess", I spent an entire weekend cleaning up the commits. You then complained that the lines were disappearing. You then said were going to fold my mods into scatter charts. . You then complained that the lines were disappearing.   I created a demo that did not use random data but used ordered data to prove my point, you have ignored this.

I believe that you should turn this project over to a person that does not look at surnames and make slurs upon their work, but clearly looks  upon the contributions and recognizes them for valid contributions.

**Comment by danielgindi** [comment]
Gerard, I'm definitely not fit to deal with people like you.

This is apparantly the first time you've worked with an open source project.

Your first try at a contribution was nice but not good enough. When working with open source projects I was required to cleanup, adjust code styling and rebase over and over again- even the smallest commits.

You were offended and sent me an *email*, saying how much you were hurt by me not accepting your PR.  
I've tried to sooth your aching heart as much as I can, instead of telling you "Please don't write to me privately anymore, use GitHub issues".

So now I'm accused with Racism? Because I've used the word "Capiche"? It's a common word in Israeli slang, and I've no idea that you are Italian, and I don't give a damn. The fact that you do that and theb mention that I'm Hebrew, is actually showing that what you are doing is the actual Racism.  
But still, I don't give a damn. Low lives like you do not deserve me even writing this response to you now.

Now to be practical:

I'm **not** sitting in front of the computer 24 hours just waiting for you to create a PR, a demo or an issue so I can review it. I have a life. I just got married and even before that I had a life. This whole project is a **volunteer** work. I **dont** work for you.  
And even when I'm accepting a big change- it requires testing, and porting to the Android platform. @Philjay and I are working closely on this framework, and you receive it on a silver plate.

You are invited to get the hell out of here, to stop using the wondeful framework, and relieve me of your presence for the rest of my life. You stupid asshole.

**Comment by gjpc** [comment]
Thanks for proving my point

**Comment by danielgindi** [comment]
Just for the record, this is the first time that I encounter references to my ethnicity in my line of work. Thanks for ruining the good name of tech guys around the world.

**Comment by danielgindi** [comment]
Anyone wants to take over this project? I'm actually getting tired of people like this.

**Comment by mythodeia** [comment]
@danielgindi i really hope you are kidding, right? Its up to you to not let anyone get in your head. Just ignore them and continue with your work/life as usual. Simple as that. Thanks for this excellent library :+1:

**Comment by danielgindi** [comment]
@mythodeia if you only knew how many laughs we had over here about this... But you know, this guys opened an issue, and claims that I don't take him seriously, so I decided to not just close the issue like that ;-)

**Comment by mythodeia** [comment]
@danielgindi i understand...but its up to you to let it go and continue with your work. I do not see any good outcome coming from this if you continue discussing it. I can see how it can hurt reading comments like that but still...
Anyway..IMHO i would suggest to let go and move on. I know there are and will be more people like this coming here but on the other side there are so even more that appreciate your 'free' work.

**Comment by liuxuan30** [comment]
Oh no I have just taken 3 days off and look at what happened here...
@danielgindi You cannot abandon this project. Calm down, close your computer, enjoy great food and having a good sleep and have fun on what's you like to do.

To @gjpc, I hope you understand how open source community pushes forward, every line of code matters so much. This is also the first time I contributed seriously to open source project in my life. We must follow the rules to try out best to make sure it does not cause new bugs, make sure it has the same quality and style as before. 

I used to make many commits in one PR (cause I don't know git a lot, just basic level), and daniel shows me how to use SourceTree and squash the commit to keep it simple and easy to read. Now I learned new skills. Those skills will only help you better when you contribute to other projects and make you more professional. 

Daniel does not know me at all, so do I. We are here because of this fabulous project and free of use. He does not want to hurt your feelings and against you. He needs to make sure what's being merged into master branch is as good as other parts, because there are so many people using it, we must be responsible.

I know you feel bad that you devote yourself in creating a good chart type so many days, I appreciate that, I respect your work. I hope you be patient, with such a big change I guess, daniel needs to think about other aspects, and as he said, this is not a job, just a volunteer work, so it needs time, time to understand, time to think, time to test, time to porting the code. I had created some bugfix PRs and it takes about 1-2 month to get reviewed and merged, and I tell myself if it has true values, it will get accepted, just a matter of time. This is what I want to tell you, patience. If it like what you think is important, just create a branch and let time prove it. There are so many good ideas for this library, but some great ones are better to be in their own branch, not in master. Master branch is for what people need most.

This is open-source and you are free to play with it, we will try to help, we want every one to make it better, since singple person has limit.

Hope every one has a good day!
