### ISSUE TITLE
Some problems about CandleStickChart

### ISSUE THREAD

**Issue by YariZhang** [danielgindi/ios-charts#348]
I want to draw stock k-line chart , so I tried to draw it with CandleStickChart , but I found that if there's few dataSets , eg. 5 candles ,  CandleStickChart drawn them in the full of content rect , it isn't I wanted , maybe I just need the width of candle is 5 or 10 , and draw them from left to right , I tried to change the width of _bodyRect , It worked , but the shadow points was wrong (as shown in figure below) . how can I do? Thank you!
![image](https://cloud.githubusercontent.com/assets/11606388/9728171/c7840cb4-5638-11e5-8c83-3f754f8c8b08.png)

**Comment by AlBirdie** [comment]
I'm sorry, but I couldn't understand what you mean. The screenshot you've given clearly shows that the candle boxes aren't drawn correctly. Is that an issue with the ios-charts library, or is that due to your own fiddling with the CandleStickChartRenderer's drawing method? If so, what is it really that you are trying to achieve?

**Comment by YariZhang** [comment]
Thanks for replying!Sorry , it’s my expression not clear enough.Yeah , that is ios-charts library . That is my modified appearance, I want to limit the width of the candle, and I don't want to draw them in full of the content rect when only a few datas .(as  figure 1 below).Now, I have achieved it , when the data is few, I fill some useless data to xVals and yVals . But by this way, it  will appear blank area when I zoom. (as  figure 2 below)So I'd like to limit the width of candle , maybe it is better.

![image](https://cloud.githubusercontent.com/assets/11606388/9730101/b915896a-5646-11e5-9bd3-fc9f6293f4d5.png)
(1)
![image](https://cloud.githubusercontent.com/assets/11606388/9730107/cc6e98f8-5646-11e5-96f2-35f6133c7177.png)
(2)

**Comment by AlBirdie** [comment]
In case you just want to decrease the width of the candles, you can make use of the counter in the CandleStickChartRenderer's drawing method. For instance; if count < 20 -> width = 10. Naturally, the formula here has to be a lot smarter, so that the width is calculated properly for all counts in a way that there are no sudden jumps of candle widths, but a smooth transition instead, just like is is done currently.

However, that will not result in what you've illustrated in figure 1. I'm afraid that will only work with empty values in your dataset.

**Comment by YariZhang** [comment]
@AlBirdie Thank you very much! I had achieved that I need . Thanks for helping me to solve this problem. If I have some other problems , I'm afraid that I'll disturb you again . Ha-ha~
