### ISSUE TITLE
Line Graph error

### ISSUE THREAD

**Issue by smilydronavalli** [danielgindi/ios-charts#396]
Hi,

When i create the any graph  I got the following error

        Could not cast value of type 'MyGraphProject.BarChartData' (0x108f67b40) to 'Charts.BarChartData' (0x10942dad0).

Pls help me for the solution

**Comment by yas375** [comment]
Could you please provide a sample app showing the issue? I guess something wrong with the setup, but with the provided info it's hard to say what's wrong.

**Comment by smilydronavalli** [comment]
Hi 

Sorry its my problem now its working fine

**Comment by davidck** [comment]
@smilydronavalli: I just ran into the same issue with it embedded into a Obj-C project.  Would you mind sharing your solution?

**Comment by liuxuan30** [comment]
@davidck you crash at `[[BarChartDataEntry alloc] initWithValue:2.0 xIndex:i]` or `yVals addObject`?

**Comment by davidck** [comment]
@liuxuan30 The crash actually occurred at addObject as you've indicated.  I've since solved the issue by cleaning up the Swift to Obj-C generated code from the bridging headers.  As such, I'm not entirely sure why this is happening in the first case, which can be based on our setup.  After the manual cleanup of the generated file, the issue happened once more and the same cleanup needed to apply.

I did not use the pod install method, but manually dragging the entire ios-chart source into the project.  I tried using the cocoapods method using the !use_frameworks directive in the pod file, but no luck.
