### ISSUE TITLE
Display X-axis and y-axis names and Can i display x axis values vertically

### ISSUE THREAD

**Issue by smilydronavalli** [danielgindi/ios-charts#403]
Hi,

Please Any one help me display x axis and y-axis Titles and display x axis coordinate names as vertically.

**Comment by liuxuan30** [comment]
Could you give an example to clarify axis title and coordinate names?

Currently it supports display axis labels already

**Comment by smilydronavalli** [comment]
Hi,

I want to display like the below image
![screen shot 2015-09-21 at 6 50 24 pm](https://cloud.githubusercontent.com/assets/14346725/9992789/e1c8a43c-6091-11e5-97f8-1574b7d90bae.png)

**Comment by liuxuan30** [comment]
For the title, I think we don't support this right now. But since it's quite simple, you could actually add the UIlabel by yourself outside of the chart view as a workaround.

For the Label directions on x axis - you need also to add your customizations in the `drawLabels` in xAxisRenderer and rewrite ChartUtils.drawMultilineText method, or create a new method to draw to get what you want. 

Feel free to reopen it if you have more questions.

**Comment by smilydronavalli** [comment]
Hi,

Can You  tell me clearly how to use drawLabels in xAxisRenderer
