### ISSUE TITLE
Why set barRect.size.height = bottom - top to be negative?

### ISSUE THREAD

**Issue by liuxuan30** [danielgindi/ios-charts#465]
@danielgindi I was looking into some details about bar chart view today, and I found that the barRect height is negative after calculation, this surprised me a little. Could you explain some details here? Also, where you made the trick to handle the negative height? I don't see you manipulate the matrix.
```Swift
var top = isInverted ? (y <= 0.0 ? CGFloat(y) : 0) : (y >= 0.0 ? CGFloat(y) : 0)
var bottom = isInverted ? (y >= 0.0 ? CGFloat(y) : 0) : (y <= 0.0 ? CGFloat(y) : 0)
...
barRect.origin.x = left
barRect.size.width = right - left
barRect.origin.y = top
barRect.size.height = bottom - top // supposed to be negative
```

**Comment by danielgindi** [comment]
It could be negative or positive, depending on the specific bar - but you don't have to do any "trick", as all rendering platforms (that I know of, including iOS and Android) take care of negative heights automatically. 
It's simple for them because they do not consider `width` and `height`, but `x1 = left`, `x2 = left + width`, `y1 = top`, `y2 = top + height`

**Comment by liuxuan30** [comment]
@danielgindi but if I try to use `barRect.size.height = abs(bottom - top)`, it actually broke the rendering.

**Comment by danielgindi** [comment]
Of course it did, you have change its direction. `y2 = (10 + (-50)) = -40` vs `y2 = (10 + abs(-50)) = 60`

**Comment by liuxuan30** [comment]
Ah I see. Thanks for the lesson!

**Comment by danielgindi** [comment]
:-)
