### ISSUE TITLE
the text rotation （Cry for help）

### ISSUE THREAD

**Issue by 931743010** [danielgindi/ios-charts#505]
old lable：
![image](https://cloud.githubusercontent.com/assets/9315727/10723054/df8f36c4-7bf1-11e5-9a47-2fc6b6cb2215.png)
new lable effect：
![image](https://cloud.githubusercontent.com/assets/9315727/10723055/e470bb18-7bf1-11e5-95c0-b444a76e332d.png)
how to rotate the label to Stand up to see more dates.

it‘s best to give a demo.

**Comment by danielgindi** [comment]
Duplicate https://github.com/danielgindi/ios-charts/issues/61

If you want to rush this - you can give it a try implementing this yourself. Basically you need to rotate the CG matrix before drawing, and you need to rotate it also when calculating the "longest label width" - to consider the angle.

**Comment by liuxuan30** [comment]
I tried once, but seems I missed something, I rotate the text and the text is gone... Must miss something like anchor point

**Comment by danielgindi** [comment]
I have just implemented this. Cheers :-)

(And yes, it was a lot of sitting with a pen, drawing bounds and angles, and figuring out what goes where...)

**Comment by 931743010** [comment]
Thank you so much for yours attention to this problem.   i  Look forward to  ，haha

**Comment by liuxuan30** [comment]
woooooow can't wait it and learn another lesson! The matrix is killing me :)

**Comment by danielgindi** [comment]
The headache here is the anchor points. You want to draw the text rotated
around its center, and align left/right only the outer box which encloses
the rotated label. So you have virtually two anchor point.
>
>
When I'll add multiline support to horizontal chart's axis labels, I'll
need to be able to specify text alignment, and compensate for that in all
that math- which I think affects Android only because it changes the
drawing anchor point according to the alignment property...
