### ISSUE TITLE
Stepped line charts

### ISSUE THREAD

**Issue by andrelind** [danielgindi/ios-charts#539]
Stepped line charts are not supported...?
If we could get that implemented then we can finally drop the huge bloat that is CorePlot from our projects...!

**Comment by ezamagni** [comment]
I agree, this would be really helpful

**Comment by danielgindi** [comment]
What's "stepped line chart"?

**Comment by ezamagni** [comment]
Take an example input of (0,0), (1, 1), (2, 2), (3, 1) and look at the (terrible) sketch below:
![steppedexample](https://cloud.githubusercontent.com/assets/6697707/13321296/82c4f482-dbce-11e5-906e-610afb8d3bef.png)

The first line is what ios-charts would draw: a linear segment connecting each point; the bottom chart is what is called a "stepped line" and it's very useful for sampled data

**Comment by danielgindi** [comment]
Man you only need about 30 minutes, cloning the `drawLinear` function in the line chart - and making it draw to start and end point of each bar instead of just to the center.

That should just be an option to toggle in the dataset to trigger stepped rendering. I do not have the time to implement this right now but I will be more than happy to review a PR :-)

**Comment by ezamagni** [comment]
Thanks for the suggestion, Daniel!  As soon as i manage to get some time i will try to play with it.

**Comment by danielgindi** [comment]
This is merged in. Thank you @ezamagni !
