### ISSUE TITLE
Issues submitting app to Apple store

### ISSUE THREAD

**Issue by 931743010** [danielgindi/ios-charts#544]
ERROR ITMS-90362: "Invalid Info.plist value. The value for the key 'MinimumOSVersion' in bundle WholeNet.app/Frameworks/Charts.framework is invalid. The minimum value is 8.0"

**Comment by petester42** [comment]
Thats is because Apple requires all frameworks to be of the same version as the app. Makes no sense but you have to change all your framework versions to match your app version. You can look at how artsy fixes this in their most recent app (see post_install method in the podfile) https://github.com/artsy/Emergence/blob/master/Podfile

**Comment by 931743010** [comment]
i use“Drag the Charts.xcodeproj to your project”. do you have any idea about this

**Comment by petester42** [comment]
Ya it's not an iOS charts problem. It's an apple problem. Read what I posted earlier. Should fix your problem.

**Comment by 931743010** [comment]
yes,i just want to know how to change Charts.xcodeproj framework versions,i think will fix my problem. thanks for read my pool english.

**Comment by petester42** [comment]
You need to change the version number in the plist

**Comment by 931743010** [comment]
which key ？i changed MinimumOSVersion to 7.0. it is no use.

**Comment by petester42** [comment]
`CFBundleShortVersionString`

**Comment by petester42** [comment]
Also iOS 7 won't work. You need to use iOS 8 and above as mentioned in the readme.

**Comment by 931743010** [comment]
thank you .this fix my problem. i change all version to iOS 8 .  thank you very much.
