### ISSUE TITLE
no data available

### ISSUE THREAD

**Issue by vigyanhoon** [danielgindi/ios-charts#585]
Can we hide grid lines, x values etc. when data is not available to the chart? If yes, is there a configuration available or will need to modify code?

![screen shot 2015-12-02 at 7 21 31 pm](https://cloud.githubusercontent.com/assets/8503526/11532485/2de95ad4-992a-11e5-8465-20127577a51d.png)

**Comment by liuxuan30** [comment]
well, by default, it it's the first time you load the chart, it will not draw anything. Do you take some actions, like filtering the data leads to no data?
You can take a look at the 'data' setter. It should not draw the grid line. 
```swift
        set
        {
            if (newValue == nil || newValue?.yValCount == 0)
            {
                print("Charts: data argument is nil on setData()", terminator: "\n")
                return
            }
            
            _dataNotSet = false
            _offsetsCalculated = false
            _data = newValue
            
            // calculate how many digits are needed
            calculateFormatter(min: _data.getYMin(), max: _data.getYMax())
            
            notifyDataSetChanged()
```
        }

**Comment by danielgindi** [comment]
I actually think that it should always not draw only when `data` is `nil`.
This should be made less ambiguous.

**Comment by liuxuan30** [comment]
@danielgindi there is one scenario: if we have a filter, when filting 'all', it show 10 bars, and if we filt and lead it to no data, the bars are still there. Would it be more proper to do a redraw and show nothing? Like leave an empty axis, range from [0,1]

**Comment by danielgindi** [comment]
Well with the latest commits- it will be more controllable, to the developer's opinion.

As long as `data` is `nil`- the "no data" will show. If you have data with zero points, then it will draw the background and axis etc.

So if you've filtered your data and got zero results- you could pass in a `nil` data to show the "no data", or you can pass an empty data to keep the chart consistent with the other by drawing the grid.

With previous versions this was not possible due to the `yValCount == 0` condition

**Comment by acegreen** [comment]
@vigyanhoon I know this is an old post but how do you show both "No data available" and the graph grid?
