### ISSUE TITLE
setLabelsToSkip does not seem to function properly

### ISSUE THREAD

**Issue by Spoonrad** [danielgindi/ios-charts#594]
Hello and thank you for this amazing framework.

I'm trying to create a HorizontalBarChart and to make sure no X label gets skipped. I tried [xAxis setLabelsToSkip:0] with no success. I've also tried, as a test, to increase the number of labels to skip using [xAxis setLabelsToSkip:3], but it does not seem to do anything.

I would like to try changing the Modulus manually but the isAxisModulusCustom property is readonly.

Thank you.

**Comment by liuxuan30** [comment]
1. the bar's height height might smaller than the label's height, so it may be skipped, otherwise it will have overlay;
2. you can change or override the source code to meet your demand.

**Comment by Spoonrad** [comment]
Hi,

1. I don't understand what this means. Overlay? If I set labelsToSkip to 0, there is no overlay, a bunch of labels are skipped, that is all.
2. I installed the framework via CocoaPods. If I change the source code, won't a pod update revert it back to your version of it when there's a new version of ios-charts? I tried subclassing HorizontalBarChartView (the bar chart View I'm using specifically), which already overrides calcModulus, but it gives me an error "Cannot subclass a class with objc_subclassing_restricted".

Thank you.

**Comment by liuxuan30** [comment]
yes, if you are using pods, I guess you need to switch to the source files, make the customization, build the framework, and embedd it. If you are supporting iOS 7, you can directly use the source files without having to embed the framework.
Currently ios-charts does not expose all the funcs to subclass or outside, that's why you have to modify it if you want override them. If you think it's good for a PR, just open one.
`I'm trying to create a HorizontalBarChart and to make sure no X label gets skipped.` 
you are trying to display every x label for horz. bar chart, but there is one situation: many y values will lead the bar to be thinner, so the label's height will larger than the bar's height, so it's possible two x labels overlayed, right?
