### ISSUE TITLE
[suggestion] Warning when wrong ChartDataSet is used for view

### ISSUE THREAD

**Issue by AndreasHeiberg** [danielgindi/ios-charts#616]
This is obviously my fault, but I had quite a lot of problems making sample code work as I had put LineChartView in my storyboard and my sample code was trying to set a BarChartDataSet.

The reason this threw me off is that everything but the data visualization loads. So you can click on a point and get the correct data, you just can't see the bar. So I was clueless as to what the problem was. If it had said "no data loaded" or "Data of incorrect type loaded" it would have been easy to debug :)

**Comment by liuxuan30** [comment]
I guess it is not a very common case ( you are the first one I guess), since you already knows there are bar chart data set and lines'. Debugging such issues should not be a huge overload. You will get faster when you used several times.

It will also crash if you feed incorrect dataSets, when you encounter forcr casting 'as!' to a wrong class.

If we see more coming, we will think about it.

**Comment by AndreasHeiberg** [comment]
Yeah just a thought. Did take me quite a while to spot :)
