### ISSUE TITLE
LineChart  xAxis can't match the point

### ISSUE THREAD

**Issue by yanglezyq** [danielgindi/ios-charts#626]
![222222222222](https://cloud.githubusercontent.com/assets/7953902/12004994/400b2e3c-abc1-11e5-813e-124d2d5e560b.jpg)

X-laebes is date, point is heart-rate value.   but them seems can't match.

There has a method or attribute I can use ?   Let LinechartView can scroll when I not doubleTap

**Comment by liuxuan30** [comment]
From your screenshot, we can't say it's drawing wrong because we don't know if 19:31 is really maps to the previous value. It's more like you are not feeding the correct data sets and entries, so they won't match. Take a look at ChartsDemo about multiple data sets and lines example.

the line chart will only scroll if you zoomed in, you can override the double tap gesture or just disable it.
