### ISSUE TITLE
Combine horizontal bar chart and line chart 

### ISSUE THREAD

**Issue by woutergoossens** [danielgindi/ios-charts#661]
Hi,

At the moment I have a chart like this which is already looking great (all line charts),

<img width="315" alt="screen shot 2016-01-09 at 17 08 29" src="https://cloud.githubusercontent.com/assets/355048/12216998/bbe767f4-b6f3-11e5-85a6-d8ba1b586658.png">
 but I need to combine a horizontal bar chart with my line charts so get a result like this.
<img width="313" alt="screen shot 2016-01-09 at 17 08 32" src="https://cloud.githubusercontent.com/assets/355048/12217001/c12e3bca-b6f3-11e5-8d84-04803ff5abd9.png">

Is that possible?

Thanks

**Comment by liuxuan30** [comment]
It's technically possible right now to combine the horizontal bar chart with a normal line chart, but it requires a very, very deep customzations, which I would suggest not to, because, this kind of chart's meaning is obscure (I doubt is there any such chart being used?)
If you just need some visual effect, you can find other ways to do it.

**Comment by tusharquantsapp** [comment]
@woutergoossens Did you find any workaround for this?
