### ISSUE TITLE
Horizontal Bar Chart Rounding

### ISSUE THREAD

**Issue by jrustonapps** [danielgindi/ios-charts#676]
Hi,

I am seeing an issue with the horizontal bar chart. I am attempting to show a bar chart with 2 - 3 values in it. There's times on the X axis and doubles on the Y axis.

The issue occurs when all of the Y values are the same. For example, if there are 2 Y values and both of them are 1.67, it's incorrectly rounding them to 2. If one of the Y values was 1.67 and the other was 2, it works correctly.

<img width="358" alt="screen shot 2016-01-13 at 16 54 00" src="https://cloud.githubusercontent.com/assets/4980957/12299385/cadca762-ba16-11e5-94aa-393720b27ac2.png">

This screenshot is taken where both values are 1.67.

<img width="347" alt="screen shot 2016-01-13 at 16 55 00" src="https://cloud.githubusercontent.com/assets/4980957/12299397/d5ad4dd6-ba16-11e5-9609-11bbc3a91d9c.png">

This is taken where one value is 1.67 and the other is 2.

The number itself is very important in this application, rounding it to 2 would not work.

**Comment by liuxuan30** [comment]
This is becuase it will calculate the digits it needs by default value formatter:
```swift
    internal func calculateFormatter(min min: Double, max: Double)
    {
        // check if a custom formatter is set or not
        var reference = Double(0.0)
        
        if (_data == nil || _data.xValCount < 2)
        {
            let absMin = fabs(min)
            let absMax = fabs(max)
            reference = absMin > absMax ? absMin : absMax
        }
        else
        {
            reference = fabs(max - min)
        }
        
        let digits = ChartUtils.decimals(reference)
    
        _defaultValueFormatter.maximumFractionDigits = digits
        _defaultValueFormatter.minimumFractionDigits = digits
    }
```
in your case only two values exists, and the reference would be 0, so the fraction digits are 0, that's why you see it's rounded, by the formatter.
What you can do is pass your valuFormater in dataSet, so you can get rid of the default formatter.
I won't consider it's a bug, because it's a default value foramtter, and it has a default logic to adjust its FractionDigits. @danielgindi what you think?
