### ISSUE TITLE
XAxis Co-Ordination with Y Axis

### ISSUE THREAD

**Issue by BurhanMughal** [danielgindi/ios-charts#68]
Hi Daniel,
Hope you are doing good.
I am having a little problem and likely unable to sort it out. 

1- How to show min number of values on XAxis
   i.e. I have to show data of three days and XAxis should contain 19 values with 4 hours difference (e.g. 4am 8am 12pm etc.). Problem is it does not show all 19 values at once.

2- How to co-ordinate xAxis with Yaxis ?
    How to co-ordinate values of xaxis with yaxis i.e. I have 3 data entries in single day and in single hour too. How to show it according to timestamp of value ?

What I tried ? 
   I tried to give XAxis directly timestamp but it does not render all three values under one hour (e.g. 5pm) rather it create three XAxis values (5pm,5pm,5pm) and render value under each entry.

Any Idea would be great.

Thanks.

**Comment by danielgindi** [comment]
Basically you'll want to play with the modulus and have a custom modulus because the system tries to hide too many x-labels.
Y axis is always the VALUE, while the X values is your "when".
So you do not "coordinate" with Y axis, you just make sure that all your datasets use the same timestamps.

Anyway, for questions regarding complex situations, or general documentation, you need to refer to the MPAndroidChart repo :-)
