### ISSUE TITLE
Continuing the last closed #695

### ISSUE THREAD

**Issue by wganeshb** [danielgindi/ios-charts#700]
@liuxuan30 Thank you very much for the quick reply.

I checked all the above scenarios. They are at its place ok. Also I checked ChartsDemo project. There delegate method is called perfectly. 

I tried these steps.
1) I directly drag and dropped the files "PieChartViewController.xib", "PieChartViewController.h", "PieChartViewController.m". from ChartsDemo project.
2) I used this pie chart as it is.

It shows the graph perfectly. But still not go in the delegate method. 

I tried 3rd hint from you. That control goes in that method. as shown in screen shot. 

![screen shot 2016-01-22 at 11 57 47 am](https://cloud.githubusercontent.com/assets/3005149/12503976/7d0ae9be-c0ff-11e5-92e3-c1ff7178026c.png)

I really need this to be done. I am really not getting what is the exact issue.

Any suggestion are highly appreciated.

**Comment by liuxuan30** [comment]
Please reply on the closed issues, don't open a new one for a follow up. I just close it because it's easy to track unsure issues. I will update closed issues as well as long as there is update.

First of all, you should know or learn how to debug and read the code. Code tells you everything. We can't teach a debug lesson here, there are many on google.

Now you have break at the gesture handler, which means the pie chart detect your touch. You can add more break points at `self.highlightValue(highlight: nil, callDelegate: true) // call delegate`, or step by step debug to see why `self.highlightValue(highlight: nil, callDelegate: true)` not being called. You can also directly add break pint inside `highlightValue` to see if it's getting called.
