### ISSUE TITLE
Realm module not found when using a static library of Realm in my pod project in Objective-C

### ISSUE THREAD

**Issue by FishForLife** [danielgindi/ios-charts#714]
Hi. I am currently building an application in iOS 8 and with XCode 7.
I dragged the Chart project to my project, linked Binary and tried to built. However, the following result occurred in Charts-Swift.h :
'Module 'Realm' not found'

I was using a static library of Realm in my pod project in Objective-C. I wonder if the Charts library can use that instead of the swift version of the Realm.
Thank you so much for your help!

**Comment by danielgindi** [comment]
It actually does. You have to link the Realm library as well.
The `Charts` framework is **not** bundles with `Realm` framework, it only references it "optionally".

**Comment by danielgindi** [comment]
`Charts` is compiled against `Realm` and `RealmSwift`, not just `RealmSwift`. You can see that the demos are in **ObjectiveC** and still work with Realm.

**Comment by kbala** [comment]
Hi @danielgindi 

I am already doing with RealmSwift, I just found this wonderful chart framework, when I try to implement with ChartsRealm, seems its built by Objective-C Realm. Its use RLMResults instead of Results<T>. 

Cant use this with RealmSwift?

**Comment by danielgindi** [comment]
Well the Swift version of Realm still does not expose everything we need - but there's a PR in Realm made by the Realm team themselves - to change that. They really want you to have the easiest integration with Charts, and hopefully it will be done soon :-)

On a side note - you could pass a table name instead of a results array, and if your use case is simple enough it will do.
