### ISSUE TITLE
cannot compile ios charts because of Ream environment missing.

### ISSUE THREAD

**Issue by skrite** [danielgindi/ios-charts#733]
greetings. I am trying to build my app with ios charts. Everything seems to import ok, i get code completion when i am  writing. but when i tried to build, i get this error. 

ld: framework not found Realm for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

i know that it's written here that I don't have to use Realm, but removing the Realm directory and checking it as "optional" did not help at all. 

i am using xcode 7.2

thanks for any tips

**Comment by liuxuan30** [comment]
As README said, you have to remove all the Realm related stuff if you don't need it.
Apparently Realm is still in your project setting, so try find it out.
`ld: framework not found Realm for architecture x86_64` is the clue, you have to remove it from framework

**Comment by skrite** [comment]
ok, thanks much

**Comment by dpuleri** [comment]
How did you solve this? I'm having the same problem after I add the Charts dependency via cocoapods.

**Comment by danielgindi** [comment]
Realm is now separate framework, so if you want to import it - you need `ChartsRealm`, otherwise everything should work smoothly. This is a change in v2.2.2 to make things easier.

**Comment by danielgindi** [comment]
Just make sure you are working with 2.2.2 or later

**Comment by dpuleri** [comment]
I hate to be a noob. But I'm using 2.2.1 since that's what came in via the cocoapod and I also am only using Charts functionality, not Realm.

However, I'm getting this sort of output from the linker whenever I try to compile:
```

Ld /Users/daniel/Library/Developer/Xcode/DerivedData/AppName-bwzdpvjkoxmrmadrvjwvntlhxqmx/Build/Products/Debug-iphonesimulator/AppName.app/AppName normal x86_64
    cd /Users/daniel/Dropbox/iOS/AppName
    export IPHONEOS_DEPLOYMENT_TARGET=9.2
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk -L/Users/daniel/Library/Developer/Xcode/DerivedData/AppName-bwzdpvjkoxmrmadrvjwvntlhxqmx/Build/Products/Debug-iphonesimulator -F/Users/daniel/Library/Developer/Xcode/DerivedData/AppName-bwzdpvjkoxmrmadrvjwvntlhxqmx/Build/Products/Debug-iphonesimulator -filelist /Users/daniel/Library/Developer/Xcode/DerivedData/AppName-bwzdpvjkoxmrmadrvjwvntlhxqmx/Build/Intermediates/AppName.build/Debug-iphonesimulator/AppName.build/Objects-normal/x86_64/AppName.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=9.2 -Xlinker -objc_abi_version -Xlinker 2 -framework Charts -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -Xlinker -add_ast_path -Xlinker /Users/daniel/Library/Developer/Xcode/DerivedData/AppName-bwzdpvjkoxmrmadrvjwvntlhxqmx/Build/Intermediates/AppName.build/Debug-iphonesimulator/AppName.build/Objects-normal/x86_64/AppName.swiftmodule -Xlinker -dependency_info -Xlinker /Users/daniel/Library/Developer/Xcode/DerivedData/AppName-bwzdpvjkoxmrmadrvjwvntlhxqmx/Build/Intermediates/AppName.build/Debug-iphonesimulator/AppName.build/Objects-normal/x86_64/AppName_dependency_info.dat -o /Users/daniel/Library/Developer/Xcode/DerivedData/AppName-bwzdpvjkoxmrmadrvjwvntlhxqmx/Build/Products/Debug-iphonesimulator/AppName.app/AppName

ld: framework not found Realm for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I feel like it may be something obvious, but I'm just too inexperienced.

**Comment by danielgindi** [comment]
As I said, use 2.2.2 and your problems will be solved.

**Comment by dpuleri** [comment]
I was looking through the issues and it seems that cocoapod 2.2.1 is the 2.2.2 branch in the main repo if I'm reading #725 correctly.

Anyways, my problem was a combination of not knowing how to use cocoapods in general and some weird setting issues. I would recommend future newbies like me [this](http://www.raywenderlich.com/97014/use-cocoapods-with-swift) tutorial--main thing is that when you use pods you have to open your project from the .xcworkspace file instead of the .xcodeproj file. Also, [this](http://stackoverflow.com/questions/26287103/cocoapods-warning-cocoapods-did-not-set-the-base-configuration-of-your-project) stackoverflow question helped me when I was getting errors about overriding project configs using the pods. 

Thanks for the help though, Daniel!

**Comment by dpuleri** [comment]
Oh another add, the reason I was getting the error from above was because I was using the 2.2.1 framework added manually and then switched to cocoa pods. But when I switched XCode still had a cache of my previous builds so I needed to delete that cache for it to build from scratch again. Another tip for troubleshooting...
