### ISSUE TITLE
Programatically scroll to end of line chart

### ISSUE THREAD

**Issue by osolano** [danielgindi/ios-charts#809]
I have a line chart that is set to only show 6 data points but the line chart loads 30 data points in total. Was wondering if there is a way to set the chart to start at the end instead of the beginning or programatically scroll to the end or last data point?

**Comment by liuxuan30** [comment]
use `moveViewToX`
Moves the left side of the current viewport to the specified x-index.
This also refreshes the chart by calling setNeedsDisplay().

**Comment by osolano** [comment]
Thank you! @liuxuan30

**Comment by bj97301** [comment]
I am having an issue when trying to move all the way to the right while hiding the right axis label: chartView.rightAxis.enabled = false
When the right axis label is hidden, moveViewToX seems to go to the right minus the space that would be there for the label.  Otherwise, moveViewToX works just fine when the right label is not hidden as shown below:

not hidden:
![not hidden](https://cloud.githubusercontent.com/assets/1450431/23683053/c88d29da-034b-11e7-8131-36481a99a0be.gif)

hidden:
![untitled](https://cloud.githubusercontent.com/assets/1450431/23682949/331fac4c-034b-11e7-8b9b-b664239836d2.gif)

**Comment by jtweeks** [comment]
Same issue here
