### ISSUE TITLE
Making HorizontalBarChartView scrolling vertically

### ISSUE THREAD

**Issue by NSri** [danielgindi/ios-charts#839]
I am using HorizontalBarChartView for displaying bars, when the bar exceeds 8 I want to make the HorizontalBarChartView scroll vertically. I tried setting 
 ```
        let maxBarToDisplay: CGFloat = 8.0
        self.horizontalBarChart.setVisibleXRangeMaximum(maxBarToDisplay)
        self.horizontalBarChart.maxVisibleValueCount = Int(maxBarToDisplay)
```
but it's not working. Even I tried this is in ChartDemo.

How can I make HorizontalBarChartView scroll vertically when it exceeds certain limit?

I had asked this question, when i searched for that I didn't see the question so posting it again. Sorry if it's a repetition.

**Comment by liuxuan30** [comment]
maxVisibleValueCount is not setting the range, but just the number of maximum visible drawn values on the chart, and only active when `setDrawValues()` is enabled. It's in the comment. So next time you are not sure the meaning, check out its comment

for horizontal bar chart, you should use `setVisibleYRangeMaximum`
like
```Objective-C
[_chartView setVisibleYRangeMaximum:4.0 axis:AxisDependencyLeft];
```
I guess you have to call it after you set the data, since it eventually is trying to modifty the matrix. and the matrix is settled down after we set the data. you can try it.

**Comment by NSri** [comment]
I am setting `setDrawValues()` to true.
Setting - `[_chartView setVisibleYRangeMaximum:4.0 axis:AxisDependencyLeft];` after setting the data for chart works fine.
