### ISSUE TITLE
Zooming an already zoomed view

### ISSUE THREAD

**Issue by whatsthebeef** [danielgindi/ios-charts#850]
In OSX If I zoom a chart using the pinch gesture and then try the same thing again it often reverts back to it's original position before realizing the zoom. If I just do a single zoom I'm able to pan afterwards without issue but then if I try zoom again the same thing happens. This behavior can be seen in the demo. 

Is this expected behavior and what effort do you think is required to make it so a zoom viewed can be zoomed again to increase the zoom further as is in IOS?

**Comment by danielgindi** [comment]
Yes, I see this, it is due to the difference of behaviour between `NSMagnificationGestureRecognizer` and `UIPinchGestureRecognizer`. `magnification` property has a `1.0` difference, [according to apple](https://developer.apple.com/library/prerelease/mac/documentation/AppKit/Reference/NSMagnificationGestureRecognizer_Class/index.html#//apple_ref/occ/instp/NSMagnificationGestureRecognizer/magnification).
